/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    NewTodoForm: typeof import('./src/components/NewTodoForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackBuilder: typeof import('./src/components/StackBuilder.vue')['default']
    TodoCompact: typeof import('./src/components/TodoCompact.vue')['default']
  }
}
